(require 'setup-evil)
(require 'setup-which-key)

(setq yi-evil-leader "<SPC>")

(evil-leader/set-leader yi-evil-leader)
(setq-default evil-escape-key-sequence "jk")

(setq yi-default-map
      '(("f" (("f" helm-find-files)
              ("p" helm-projectile-find-file)
              ("s" save-buffer))
         "Files")
        ("b" (("b" helm-mini)
              ("p" helm-projectile-switch-to-buffer)
              ("j" swbuff-switch-to-next-buffer)
              ("k" swbuff-switch-to-previous-buffer)
              ("o" ace-window)
              ("d" kill-buffer))
         "Buffers")
        ("p" (("h" helm-projectile)
              ("p" helm-projectile-switch-project))
         "Projectile")
        ("r" (("y" helm-show-kill-ring)
              ("m" helm-all-mark-rings))
         "Rings")
        ("s" (("b" helm-occur)
              ("p" helm-projectile-ag))
         "Search")
        ("n" (("r" narrow-to-region)
              ("p" narrow-to-page)
              ("f" narrow-to-defun)
              ("w" widen))
         "Narrow")
        ("j" (("b" avy-pop-mark)
              ("j" evil-avy-goto-char)
              ("J" evil-avy-goto-char-2)
              ("l" evil-avy-goto-line))
         "Jump")
        ("g" (("s" magit-status))
         "Git")
        ("<SPC>" helm-M-x)
        ("!" shell-command)
        ("u" universal-argument)))

;; Populate all keybindings defined in a map.
(defun yi/set-keybindings (key def &optional doc)
  (unless (null doc)
    (which-key-add-key-based-replacements (concat "<SPC> " key) doc))
  (if (listp def)
      (mapc (lambda (x) (apply #'yi/set-keybindings (concat key (pop x)) x))
            def)
    (evil-leader/set-key key def)))

(mapc (lambda (x) (apply #'yi/set-keybindings x))
      yi-default-map)

(provide 'setup-evil-keybindings)
